# -*- coding: utf-8 -*-
"""Copie de Shoe_Sales_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jK87cSpRvjwj1cHXpoUJ2s-TTAdXhxuf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style="whitegrid", palette="muted")

df = pd.read_csv("/content/shoes_sales_dataset.csv")
df.head()

"""**Understanding Data**"""

df.info()

df["Date"] = pd.to_datetime(df["Date"],errors="coerce")
df["Quarter"] = pd.to_datetime(df["Date"]).dt.quarter
df["Year"] = pd.to_datetime(df["Date"]).dt.year
df["Month"] = pd.to_datetime(df["Date"]).dt.month

df.duplicated().sum()

df.groupby("Brand")["Price_USD"].mean()

cols = df[["Brand", "Shoe_Type", "Color","Sales_Channel"]].columns

for col in cols:
    plt.figure(figsize=(8, 5))
    df[col].value_counts().plot(kind="barh",color="blue")
    plt.title(f"Count of {col}")
    plt.show()

"""**sales analysis**"""

df.columns

"""**The correlation coefficient between the price and the number of units sold is almost non-existent ($-0.015$). This means that the store's customers are not affected by price increases or decreases, which gives the management an opportunity to raise the prices of some exclusive models without the fear of losing sales**"""

df[["Price_USD","Units_Sold","Revenue_USD"]].corr()

a = df.groupby("Brand")["Units_Sold"].sum().sort_values(ascending=False)
a

a.plot(kind="barh", figsize=(10, 5),color="blue")
plt.title("Total Sales by Brand")
plt.xlabel("Total Sales")
plt.ylabel("Brand")

c = df.groupby("Brand")["Revenue_USD"].sum().sort_values(ascending=False)
c

c.plot(kind="barh", figsize=(10, 5),color="blue")
plt.title("Total Revenue by Brand")
plt.xlabel("Total Revenue")
plt.ylabel("Brand")

"""**Backed by the near-zero correlation which signals low price sensitivity, we strongly recommend implementing a strategic upward price adjustment for high-volume, lower-revenue brands like Puma. This data-driven intervention will successfully bridge the pricing gap and translate strong customer demand into maximized profit margins and higher gross revenue, without the risk of losing sales volume.**"""

c = df.groupby("Country")["Brand"].value_counts().sort_values(ascending=False).unstack()
c

c.plot(kind="barh", figsize=(10, 5))
plt.title("Count of brand in  Country")
plt.xlabel("Count of brand")
plt.ylabel("Country")

df.columns

c = df.groupby(["Country","Brand"])["Revenue_USD"].sum().sort_values(ascending=False).unstack()
c

c.plot(kind="barh" , figsize=(20, 9))
sns.set_theme(style="whitegrid", palette="muted")
plt.title("Total Revenue by Country")
plt.xlabel("Total Revenue")
plt.ylabel("Country")

"""High-Efficiency Brands (Deserve More Expansion): Puma in France and New Balance in Germany & India show outstanding performance. These brands generate premium revenue despite having moderate to low inventory/sales counts, indicating high profit margins and strong regional demand.

Low-Efficiency Brands (Over-represented): Nike in Germany and India shows a clear operational inefficiency. It maintains a high count/frequency but yields the lowest total revenue compared to its peers, proving it does not justify its current repetitive footprint in these specific markets.

Recommendation:

Optimize Inventory and Allocation: Increase the frequency, stock, and variety of Puma in France and New Balance in Germany and India to aggressively capture the high-yielding demand.

Downsize Underperforming Brands: Reduce the repetition and visibility of Nike in the German and Indian markets, reallocating that operational capacity to high-margin brands like Skechers and New Balance to maximize overall profitability *
"""

c = df.groupby("Country")["Revenue_USD"].sum().sort_values(ascending=False)
c

c.plot(kind="barh", figsize=(10, 5),color="blue")
plt.title("Total Revenue by Country")
plt.xlabel("Total Revenue")
plt.ylabel("Country")

z = df.groupby(["Brand","Shoe_Type"])["Revenue_USD"].sum().sort_values(ascending=False).unstack()
z

z.plot(kind="bar", figsize=(20, 10))
plt.title("Total Revenue by Brand")
plt.xlabel("Total Revenue")
plt.ylabel("Brand")

df.columns

v = df.groupby(["Shoe_Type","Country"])["Revenue_USD"].sum().unstack()
v

v.plot(kind="bar", figsize=(20, 10))
plt.title("Total Revenue by Shoe Type")
plt.xlabel("Shoe Type")
plt.ylabel(" Total Revenue")

"""High-Yield Opportunities (Growth Drivers): Boots command an extraordinary revenue milestone in the USA, with New Balance and Skechers driving the highest returns in this category. Concurrently, Sneakers represent the primary revenue pillar in France and the UAE, heavily driven by Adidas’ stellar performance.

Low-Yield Deadweight (Loss Prevention): Sports and Running shoes exhibit poor performance and minimal revenue generation in the UK and Saudi Arabia, indicating that high inventory allocation in these categories results in deadstock and operational inefficiencies.

Recommendation:

Aggressive Expansion on High-Performers: Allocate aggressive inventory budgets to Boots in the USA market (leveraging New Balance/Skechers) and Sneakers in France and the UAE (leveraging Adidas) to capture high-margin turnover.

Inventory Downsizing & Mitigation: Strategically reduce the supply of Sports and Running shoes in the UK and Saudi Arabian branches. Reallocate that operational capital and shelf space toward locally preferred categories, such as Formal shoes in the UK, to eliminate waste and maximize ROI.
"""

x = df.groupby(["Brand","Shoe_Type","Country"])["Revenue_USD"].sum().sort_values(ascending=False).unstack()
x

c = df.groupby("Color")["Revenue_USD"].sum().sort_values(ascending=False)
c

c.plot(kind="barh", figsize=(10, 5),color="blue")
plt.title("Total Revenue by Color")
plt.xlabel("Total Revenue")
plt.ylabel("Color")

b = df.groupby(["Color","Shoe_Type"])["Revenue_USD"].sum().sort_values(ascending=False).unstack()
b

b.plot(kind="bar", figsize=(20, 10))
plt.title("Total Revenue by Color")
plt.xlabel("Color")
plt.ylabel(" Total Revenue")

n = df.groupby(["Color","Brand"])["Revenue_USD"].sum().unstack()
 n

n.plot(kind="bar", figsize=(20, 10))
plt.title("Total Revenue by Color")
plt.xlabel("Color")
plt.ylabel(" Total Revenue")
plt.grid(True)

df.groupby(["Color","Shoe_Type","Brand"])["Revenue_USD"].sum().unstack()

"""High-Yield Combinations (The Winners): Green Formal shoes emerge as a major revenue driver. Additionally, Grey Boots (highly driven by Skechers and New Balance) and Black Casual shoes (led by Puma at over 20,129) show exceptional market demand and premium revenue generation.

Low-Yield Combinations (The Underperformers): White Casual shoes and Black Boots generate remarkably low revenue across almost all brands (e.g., Adidas Black Boots yielding only 1,466), indicating low consumer preference for these specific item mixes.

Recommendation:

Double Down on High-Performers: Aggressively expand inventory allocation for Green Formal shoes, Grey & Blue Boots (leveraging Skechers/New Balance), and Black Casual lines from Puma to maximize high-margin sales.

Phase Out and Mitigate Low-Performers: Cut back orders for Black Boots across underperforming brands and reduce exposure to White Casual footwear. Reallocate that open inventory budget toward the dominant color palettes (Grey, Blue, and Green) to optimize stock turnover, eliminate shelf wastage, and boost overall gross margins.
"""

x = df.groupby("Sales_Channel")["Revenue_USD"].sum().sort_values(ascending=False)
x

x.plot(kind="barh", figsize=(10, 5),color="blue")
plt.title("Total Revenue by Sales Channel")
plt.xlabel("Total Revenue")
plt.ylabel("Sales Channel")

p = df.groupby(["Sales_Channel","Brand"])["Revenue_USD"].sum().sort_values(ascending=False).unstack()
p

c = df.groupby(["Sales_Channel","Country"])["Revenue_USD"].sum().unstack().sort_values(ascending=False,by="Sales_Channel")
c

c.plot(kind="bar", figsize=(20, 9))
plt.title("Total Revenue by Sales Channel")
plt.xlabel("Sales Channel")
plt.ylabel(" Total Revenue")
plt.grid(True)

"""Digital Dominance: The Online channel delivers extraordinary, peak performance in the UAE and Saudi Arabia, demonstrating massive digital adoption and mature e-commerce penetration in the GCC region.

Brick-and-Mortar Preference: Consumers in Germany and the UK show a powerful, clear preference for Malls, while France and the USA sustain high-volume leadership via independent Retail Stores.

Recommendation:

Aggressive Digital Scaling: Maximize digital marketing spend, localized ad campaigns, and UI/UX optimization targeting the UAE and Saudi Arabian markets to ride the high-yielding online wave.

Physical Footprint Reinforcement: Expand stock allocation and premium display setups in German and UK Malls, while focusing on loyalty programs and in-store experiences within French and US Retail Stores.

Mitigating Germany's E-Commerce Gap: Investigate the massive online underperformance in Germany (under 40,000). Implement targeted web-only promotions or localized digital incentives to tap into the unrealized online potential of the German consumer base.

**Time analysis**
"""

df.groupby("Month")["Revenue_USD"].sum().plot(kind="line",color="blue",marker="o")

df.groupby("Quarter")["Revenue_USD"].sum().plot(kind='line',color="blue",marker="o")

for brand in df["Brand"].unique():
    plt.figure(figsize=(8,4))

    df[df["Brand"] == brand] \
        .groupby("Month")["Revenue_USD"] \
        .sum() \
        .plot(marker="o")

    plt.title(f"Monthly Revenue - {brand}")
    plt.xlabel("Month")
    plt.ylabel("Revenue (USD)")
    plt.grid(True)

"""Based on the analysis of the brand sales charts, here are the strategic and marketing recommendations to improve revenue and inventory management:

1. Capitalizing on Peak Seasons
Focus efforts on the Fourth Quarter (Q4): The data shows that the fourth quarter is by far the strongest, with total revenue exceeding $400,000. This is mainly driven by the massive surge for Adidas in October (Month 10), approaching $40,000, and the strong, steady growth for Nike in the last three months of the year, with sales hovering around $25,000.

Recommendation: Allocate the largest share of paid advertising budgets and year-end promotions (such as Black Friday) to this period.

Invest in the summer recovery wave: New Balance experiences a strong surge and peaks in July (Month 7), exceeding $35,000, while Skechers achieves its highest sales in August (Month 8), crossing the $30,000 mark.

Recommendation: Launch marketing campaigns for comfortable summer shoes, travel, and trips starting from May to align with this upward trend.

2. Managing Cyclical Slumps and Inventory
Countering the sharp August slump: A sudden and significant decline is observed for several brands in August (Month 8); New Balance sales drop below $10,000, and Adidas falls to its lowest levels around $11,000, negatively impacting the overall sales curve.

Recommendation: Avoid overordering new inventory from these companies in August. Instead, rely on "Back to School" promotions and summer clearances to liquidate current stock.

Addressing the Skechers decline in September and November: Skechers sales drop significantly in September (Month 9) to below $10,000, and this slowdown repeats in November (Month 11).

Recommendation: Revitalize sales during these slow months by offering exclusive deals (such as product bundles or free shipping) to incentivize buyers.

3. Brand Positioning and Ad Rotation
Relying on Nike as a core pillar: Nike is characterized by highly stable and consistent growth in the second half of the year, specifically from October to December.

Recommendation: Secure sufficient inventory of Nike in advance to guarantee a stable and assured cash flow during the final quarter.

Smart rotation between Puma and Reebok: Puma achieves excellent sales in February (Month 2) and at the beginning of summer (June and July), whereas Reebok starts the year very strong in January (Month 1), then declines before bouncing back again in December.

Recommendation: Create a rotation schedule for product displays; highlight Puma on the storefront in February and during the summer, and shift the advertising focus to Reebok in January and at the end of the year.

# Nouvelle section

**The probleme:**
**The store's inability to accurately predict monthly sales volumes for each individual brand based on temporal factors and seasonality, leading to poor inventory management and fluctuating profits.**
"""

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler

df.columns

# 1. ترتيب البيانات زمنياً لضمان أن بايثون يفهم تسلسل الأشهر والسنوات
df = df.sort_values(by=['Brand', 'Country', 'Year', 'Month']).reset_index(drop=True)

# 2. إنشاء ميزة الـ Lag الفعالة (إيرادات الشهر السابق)
# هذه الميزة ستعلم النموذج كم كانت مبيعات الماركة في نفس الدولة الشهر الماضي كمؤشر أساسي
df['Last_Month_Revenue'] = df.groupby(['Brand', 'Country'])['Revenue_USD'].shift(1)

# تعبئة قيم الشهر الأول (التي ستكون فارغة NaN) بمتوسط إيرادات تلك الماركة
df['Last_Month_Revenue'] = df.groupby('Brand')['Last_Month_Revenue'].transform(lambda x: x.fillna(x.mean()))

# 3. الآن نقوم بترميز الميزات النصية كالمعتاد
df_encoded = pd.get_dummies(df, columns=['Brand', 'Sales_Channel', 'Shoe_Type', 'Color', 'Country', 'Sale_ID'], drop_first=True)

# 4. تحديد المتغيرات (مع استبعاد الأعمدة غير الرقمية وعمود الهدف)
X = df_encoded.drop(columns=["Revenue_USD", "Date"], axis=1)
y = df_encoded["Revenue_USD"]

# 5. إعادة تقسيم البيانات
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.2, random_state=42)

df.dtypes

model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, Y_train)

model.score(X_train, Y_train)

y_pred = model.predict(X_test)

mae = mean_absolute_error(Y_test, y_pred)
print(f"Mean Absolute Error (MAE): ${mae:.2f}")

r2 = r2_score(Y_test, y_pred)
print(f"R2 Score (Model Accuracy): {r2 * 100:.2f}%")

from xgboost import XGBRegressor

xgb_model = XGBRegressor(n_estimators=100, learning_rate=0.05, random_state=42)
xgb_model.fit(X_train, Y_train)

y_pred_xgb = xgb_model.predict(X_test)
print(f"XGBoost R2 Score: {r2_score(Y_test, y_pred_xgb) * 100:.2f}%")